name: Run SNYK Monitor

on:
  pull_request:
    types:
      - closed

jobs:
  security:
    if: github.event.pull_request.merged == true
    uses: dvsa/.github/.github/workflows/java-snyk-update.yaml@v3.2.1
    with:
      java_version: 11
      snyk_project: smc-w53
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      USER_NAME: ${{ secrets.SMC_USER_NAME }}
      ACCESS_TOKEN: ${{ secrets.SMC_ACCESS_TOKEN }}
      PACKAGE_REPO: ${{ secrets.SMC_PACKAGE_REPO }}
